# Generated by Django 3.2.5 on 2021-07-25 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-title'], 'verbose_name_plural': 'statuses'},
        ),
        migrations.AddField(
            model_name='event',
            name='contract_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='crm.contract'),
            preserve_default=False,
        ),
    ]
